### ISSUE TITLE
Consider matching array_slice behavior instead of NotSatisfiableException

### ISSUE THREAD

**Issue by scotttrinh** [ramsey/http-range#1]
What is your opinion of changing the behavior of `parseRange` to match the same behavior as `array_slice` instead of throwing `NotSatisfiableException`s?

## Example 1:

```php
parseRange('0-300', 0); // => Throws NotSatisfiableException
array_slice([], 0, 300); // => []
```

When the entity has a `totalSize` of `0` you have to know that fact before requesting the range to avoid throwing an error.

## Example 2:

```php
parseRange('2-5', 1); // => Throws NotSatisfiableException
array_slice([0], 2, 5); // => []
```

The current behavior certainly makes sense (why would you request a random out-of-range range?), but it seems like conforming to a known interface/behavior like `array_slice` has some value.

**Comment by mdeboer** [comment]
Because the current behaviour is in compliance with the RFC. When the NotSatisfiableException is thrown you should respond with the HTTP status code 416 (Range Not Satisfiable).

See: https://tools.ietf.org/html/rfc7233#section-4.4

**Comment by ramsey** [comment]
@scotttrinh and I discussed this a while back, and I decided against this. I forgot to close the issue. :smile:
